### ISSUE TITLE
Implementation of Yahi in my current project

### ISSUE THREAD

**Issue by xdarkfirestorm** [devbotas/yet-another-homie-implementation#1]
Hi @devbotas 
I want to use your package in my current project. I want to turn a raspberry pi into a led controller. I already soldered and wired all the electrical stuff and want to use homie to make a nice OpenHAB implementation. For that i'd need a ClientColorProperty. I'm using transistors and i will control them via PWM.

Are you already implementing this property type? Should i initiate with a pr? Do you want this to be listed on the Homie implementations? Is your package already usable for that scenario? Are you already writing a readme file?

Thanks for the work done!

**Comment by xdarkfirestorm** [comment]
Oh btw i would also like to make my project public when i finished and will probably reference your project if it works. I also thought about my own Homie NuGet Package but saw that you already started someting.

**Comment by devbotas** [comment]
Oh wow didn't expect people finding my experiments so fast :)

I'm still experimenting a lot with the concept, so it's a bit early for readme files, but my current approach kinda works:
![image](https://user-images.githubusercontent.com/71982803/106363496-91776380-6331-11eb-9b66-d5225bed22bf.png)

I was kind of planning to implement DateTime and Color properties next week, since integers, string, floats and booleans are mostly working, so everything else is pretty straightforward. Now that I unexpectedly have a first consumer, I may create a readme.md, too :)

**Comment by devbotas** [comment]
@xFirestorm There's some support for Color property. At least OpenHAB and Hodd undestands it:

![colorkindaworks](https://user-images.githubusercontent.com/71982803/107116024-4f8e7600-6879-11eb-8fa6-de46923d270e.gif)
